### ISSUE TITLE
Local host docker server isnt responding

### ISSUE THREAD

**Issue by dhiraj-02** [elit30/decentralized-discord#1]

**Comment by dhiraj-02** [comment]
, Its saying cannot connect can you please help, my email: 01fe20bcs117@kletech.ac.in

**Comment by atharva-vyas** [comment]
Hi Dhiraj,
1) Create three instances of the docker image, and start them
2) get local ip's of all the three containers, using: `docker inspect <container_name> | grep IPAddress`
3) for each container, open /home/serverInit.json
4) replace the `myUrl` variable with the IP address of the current server that you got from step #2
5) change the `serverName` variable if you want. NOTE: server name needs to be the same for all containers
6) in the `initialNodes` array, put the IP addresses of the other two containers

ok, now for the middleware:

1) open backend/middleware/serverInfo.json in a NEW* container or on your local machine
2) populate the `initialNodes` array with the IP Addresses of the three containers from step #2
3) run backend/middleware/index.js (it will run on port 3001)
4) to check if everything is running you can go to localhost:3001/state. If you see a sha256 along with some other information like the IP's of two nodes, etc. it is running fine
5) start the frontend

Im also attaching a image to help you better understand what allthe  different pieces do..
![570e0dc6-a84b-493c-821d-a04659431e32 sketchpad(7)](https://user-images.githubusercontent.com/85245060/224796442-022b2ca3-ef67-4fcd-ac41-40a6cdb7d5c1.png)

**Comment by atharva-vyas** [comment]
also you need to start the /backend/node/index.js in all of the three docker containers, after you are done following steps #1-#6 of part one.

to do that you can simply go to /home/ and type `npx nodemon`, and that should start the server up.
